travis:
  secure:
    BINSTAR_TOKEN: mg3MTBQKhLqBRLFyO7aNHFRTFaWEEhDN9od+XpYfMyaUeTdlHQAGbduHSSjzF431XmwTHSr3FHn7bRtU7+7so/tuyiYetq0nJbkUoOTLN5upQCAZNKVk19Y9s4kRHRNn0PuJgOnyrJ+ado8WRAaGDtwR09ehB4Be9uZK0EJ55UVcHA0FTsouxbKPJ68iaX6aR1Cx8ofUdtm/qXCOlLUJD/kdtC5xuyk8aRhXWCvzSV0sdt08s4QjHl7P76zLWNaOdVqKQkezQ0tAHAJK2wQBxivJYGMKNOk1L9H9TWv61A3zG/Myn/pS9Qa/iuDqE6yddsuV3x4oVUHkGpE9PThSYnupE6BQjFl163x/RqLMlt9/peeRFW+LQsForBuxvWYb2KA+NS3fK304/gl3WanElHS9P0UkDpfnvWxs9gMh/cTgFDJSyRt55l5MyEtwNJtcl3gVCfDJL6ByGPrUduCAQ6t2rwmrSaks6cCSbI4VrBZ6ibaTWk0i4RsuY7U6lKfp+7V7Pwy+s6YZv+aM7iCwV+c3VK7rDtdRppNw2HguYVGvfA0u+5ktFeh6BV8g4KRkWL5U2ozrEG1naE4P8FodN5SiVl10usOP6VBoHO9uKEToacRdsAk3dLmihJdslrdFqefQt60Y7KwtM/9CNwWoJRFyeH9dguhe/B2hljrbDMU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
