travis:
  secure:
    BINSTAR_TOKEN: GEn8Uuo7sZMZ6YR9HFbaBOgN6PoWBDOmTInd+OMMCIFZ+5zQZFWM82HCEV0CzyE54u1cR1MFFbkyrRyNSutO48qF2t1dxWms1tNipJkvSpy20lAAOFscyZ1ptVJHVlut181Jz8LW2jh18494Ij1aCx3lRytdRAsTKDYJbzj0Cpfz6SyCuURHIxTG1y15JbvBIRobWkjzcJiKLE79Sf8ADjczVUbfEhKpWvFf7FU9/QsNUZPxjjUAsaWu22RxUabmNtxRW4XyNj/n7esd/v2NeA000oZFs9k0nGj1Qd4AGa5gQbvjGHr0qXMS18T84Y66HlIvwkoRNOyDQl16f9cm6k7TDNd/ppa7qLuwZhKdYUDwCennFZg6XdtOALG2B8wDoPYzhAaheki/GQwcTxZK9PvX3jvrfgO39nqhcZpFvGAqcLf0KBZKP1iglZvBMOfZG6jI3H5mf6YXUjXYsOZhSpRbGTrqcgvelJdlLcU+CI4xmTrfUzC/f6jZ8etFJfV4mug/tiNp9P8cwhfFfBQQSsZIE0YkhFaf1kRcGK3QrZjzZxbzt/uMUMiFnonlCWoVwhpieYPtjB+qqPVLLvp2fCcXkQZuHQ99fJ2XHepFzYW2itN+vuyG/UQfZGmfxTbWCNlE657vy3quH1ReOr5urtoGaQ0vmUsMpwj5nE3FSkg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
